### ISSUE TITLE
Make an ajax request after sleep mode

### ISSUE THREAD

**Issue by MoogyG** [mikebronner/laravel-caffeine#78]
I don't see anything in javascript side handling this case.

Should we add an observer on page visibility or something else to ensure that we have to make an ajax call?

For me, "setInterval" is not sufficient in this case because if I am not wrong, in sleep mode, javascript just pause and get alive after. So it could spend hours between 2 ajax calls.

**Comment by mikebronner** [comment]
Hi @MoogyG, do you have a solution in mind?

**Comment by MoogyG** [comment]
Hi,

I made a quick test with this : https://github.com/serkanyersen/ifvisible.js

I wrote a setinterval every 500 ms and start it, then i enter in sleep mode, i wait 2 or 3 minutes and when i power on, it fires the event "idle". 

Maybe you could extract the code for this event, and when it fires, check the timestamp of the last ajax request and call it if necessary.

**Comment by mikebronner** [comment]
Thanks @MoogyG, will look into this. :) Give me a few days, since I'll probably be busy with other things over the holiday week (Christmas and New Year). 

Happy Holidays!

**Comment by MoogyG** [comment]
I am not sure that's a proper way and even if HTML5 could cover our case by another way.

Happy Holidays Mike.

**Comment by ItaloBC** [comment]
This is covered by #72.

There is no way to tell the browser to NOT throttle its Javascript Engine when the window goes inactive. Even so, It shouldn't be a problem because `setTimeout` [can be delayed by just mere seconds](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified). The throttling (or halting in some cases) is handed differently by each browser.

Anyway, forcing the browser to dip when the window is not active should be avoided, because:

- There is no reliable way to force a dip on time, or even force one.
- Makes the browser consume more battery.
- The JavaScript Engine resumes anyway when the window becomes active, and so the script's "Check if we need to reload the whole page" part.

That script part could be handy for fire instantly when the page becomes active, like `window.on('from-idle-to-active', () => { ... })` but I don't see any critical scenario to include more lines of code if its checked anyway in 2 seconds.
